variables:
  global_variable: global
jobs:
  - job: job1
    pool:
      vmImage: 'ubuntu-16.04'
    variables:
      job_variable1: job_var1 
    steps:
      - bash: echo $(global_variable)
      - bash: echo $(job_variable1)
      - bash: echo $JOB_VARIABLE1
      - bash: echo $GLOBAL_VARIABLE
      - bash: echo $(mySecret)
