parameters:
  - name: myStringName
    type: string
    default: a string vale
  - name: myMultiString
    type: string
    default: default
    values:
      - default
      - ubuntu
  - name: myNumber
    type: number
    default: 2
    values:
      - 1
      - 2
      - 4
  - name: myBoolean
    type: boolean
    default: true
steps:
  - ${{ each paramter in parameters }}:
    - script: echo ${{ paramter.Key}}
    - script: echo ${{ parameter.Value}}