parameters:
  - name: configs
    type: string
    default: 'x86,x64'
trigger: none
stages:
  - stage: stg1
    jobs: 
      - ${{ if contains(parameters.configs, 'x86') }}:
        - job: x86
          steps:
            - script: echo building x86 ...
      - ${{ if contains(parameters.configs, 'x64') }}:
        - job: x64
          steps:
            - script: echo building x64

  - stage: stg2
    jobs: 
      - ${{ if contains(parameters.configs, 'x86') }}:
        - job: x862
          steps:
            - script: echo building x862 ...
      - ${{ if contains(parameters.configs, 'x64') }}:
        - job: x642
          steps:
            - script: echo building x642