stages:
  - stage: A
    jobs:
      - job: A1
        steps:
          - bash: |
              echo "##vso[task.setvariable variable=sauce;isOutput=true]crushed tomatoes"
              name: vartest
          - bash: |
              echo $(sauce)
          - bash: |
              echo $SAUCE
  - stage: 
    jobs:
      - job:
        steps:
          - bash: |
              echo $[ stagedependencies.A.A1.outputs['vartest.sauce']]