variables:
  configuration: debug
  platform: x64
stages:
  - stage: 
    displayName: stage1
    jobs:

      - job: 
        variables:
          key1: values1
        steps:
          - script: echo  $KEY1
