parameters:
  - name: image
    displayName: Pool image
    type: string
    default: ubuntu-latest
    values:
      - windows-latest
      - vs2017-windows
      - ububtu-latest
trigger: none
jobs:
  - job: build
    displayName: build
    pool:
      vmImage: ${{ parameters.image }}
    steps:
      - script: echo building $(build.BuildNumber) with ${{ parameters.image }}