parameters:
  - name: image
    displayName: Pool image
    type: string
    default: ubuntu-latest
    values:
      - windows-latest
      - ubuntu-latest
  - name: test
    displayName: Build and Test
    default: false
    type: boolean
trigger: none
jobs:
  - job: build
    displayName: builds
    pool:
      vmImage: ${{ parameters.image }}
    steps:
      - script: echo building $(build.BuildNumber) with ${{ parameters.image }}
      - ${{ if eq(parameters.test, true) }}:
        - script: echo "Running all the tests"
