variables:
  ${{ if eq(variables['Build.SourceBranchName'], 'master') }}: # only works if you have a master branch
    stageName: prod

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo ${{variables.stageName}}
- bash: echo $(stageName)
- bash: echo $[variables.stageName]