stages:
  - stage: firststg
    jobs:
      - job: firststg-firstjob
        steps:
          - script: echo Hello!
            condition: always()
      - job: firststg-secondjob
        dependsOn: firststg-firstjob
        condition: failed()
        steps:
          - bash: echo "sxxx"
