parameters:
  - name: configs
    type: string
    default: 'x86,x64'
trigger: none
stages:
  - stage: parameter
    jobs: jobs1
      - ${{ if contains(parameters.configs, 'x86') }}:
        - job: x86
          steps:
            - script: echo building x86 ...
      - ${{ if contains(parameters.configs, 'x64') }}:
        - job: x64
          steps:
            - script: echo building x64
  - stage: stg2
    jobs: jobs2
      - job: st2j1
        steps:
          - script: echo "stgasadf"
