variables:
- name: one
  value: initialvalue
steps:
  - script: |
      echo ${{variables.one}}
      echo $(one)
    displayName: First variables pass
  - bash: echo '##vso[task.setvariable variable=one]secondvalume'
    displayName: set new value
  - script: |
      echo ${{variables.one}}
      echo $(one)
    displayName: First variables pass      
