trigger:
  branches:
    - master
stages:
  - stage: "test"
    displayName: "testdisplay"
    dependsOn: 
    jobs:
      - job: "testjob"
        steps:
          - bash: echo "ok"
  - stage: "testq"
    displayName: "testdisplayq"
    dependsOn:
      - test
    condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/test'))
    jobs:
      - job: "testjoba"
        steps:
          - bash: echo "odkadsaf"
    