stages:
  - stage: 
    jobs:
      - job: 
        steps:
          - bash: |
              echo "##vso[task.setvariable variable=sauce]crushed tomatoes"
          - bash: |
              echo $(sauce)
          - bash: |
              echo $SAUCE