parameters:
  - name: image
    displayName: param
    type: string
    default: ubuntu-latest
    values:
      - ubuntu-latest
      - macOs-10.14
jobs:
  - job: first
    displayName: first
    pool:
      vmImage: ${{parameters.image}}
    steps:
    - script: echo $(Build.BuildNumber) with ${{paramters.image}}
