stages:
  - stage: firststg
    jobs:
      - job: firststg_firstjob
        steps:
          - script: echo Hello!
            condition: always()
      - job: firststg_secondjob
        dependsOn: firststg_firstjob
        condition: failed()
        steps:
          - bash: echo "sxxx"
