stages:
  - stage: "test"
    displayName: "testdispxlay"
    dependsOn: 
    jobs:
      - job: "testjob"
        steps:
          - bash: echo "ok"
  - stage: "testq"
    displayName: "testdisplayq"
    dependsOn: []
    jobs:
      - job: "testjoba"
        steps:
          - bash: echo "oka"
    