variables:
  configuration: debug
  platform: x64
steps:
  - task: MSBuild@1
    displayName: ${{ variables.platform }}
    inputs:
      solution: solution1.sln
      configuration: $(configuration)
      platform: $(platform)
  - task: MSBuild@1
    inputs:
      solution: solution2.sln
      configuration: $(configuration)
      platform: $(platform)