parameters:
- name: myStep
  type: step
  default:
    script: echo my step
- name: mySteplist
  type: mySteplist
  default:
    - script: echo step one
    - script: echo step two

jobs:
  - job: stepList
    steps: ${{ parameters.mySteplist }}
  - job: myStep
    steps:
      - ${{ parameters.myStep }}
