variables:
  staticVar: 'dsa'
  compileVar: ${{variables.staticVar}}
  isMain: $[eq(variables['Build.SourceBranch'], 'refs/heads/master')]

steps:
  - script: |
      echo ${{ variables.staticVar}}
      echo $(complieVar)
      echo $(isMain)