variables:
  configuration: debug
  platform: x64
stages:
  - stage: 
    displayName: stage1
    jobs:
      variables:
        key1: values1
      - job: 
        steps:
          - script: echo "s1j1s1 ${{ variables.key1 }}"
